---
title: "Introduction to splyr"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to splyr}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
library(helpr)
library(splyr)
s_data <- splyr:::sample.adat
knitr::opts_chunk$set(
  collapse = TRUE, comment = "#>"
)
```



The `splyr` package contains the general functions necessary 
to manipulate internal R representations of adat files and wrangle those
data into convenient form for analysis.


--------------------


## Useful functions in `splyr`

### Transforming Data

* `center_scale()`
* `create_recipe()`

```{r center-scale-recipe}
scaled <- center_scale(mtcars)               # all numeric features
apply(strip_meta(scaled), 2, mean) |> sum()  # mean = 0
apply(strip_meta(scaled), 2, sd)             # sd = 1

# `create_recipe()`
rcp <- create_recipe(mtcars, feat = c("mpg", "disp", "drat", "wt"))
rcp
```

-----------

### Imputing Data

* `remove_outliers()`
* `impute_outliers()`
* `imputeNAs()`
* `impute_predictors()`

```{r imputing}
# Identify outliers (`helpr::get_outliers()`)
x <- withr::with_seed(1, rnorm(10))   # normal
x <- c(x, 100)                        # add outlier
get_outliers(x)                       # get index of the outlier

# parameters stored in attributes (parametric only)
attributes(get_outliers(x, type = "para"))

# Impute 11th value
impute_outliers(x)

# Impute NAs
x <- withr::with_seed(1, rnorm(6))
x[ c(3, 5) ] <- NA
median(x, na.rm = TRUE)

imputeNAs(x)

table(imputeNAs(x))

# Predictors
x   <- data.frame(a = 1:3, b = 4:6, c = 7:9, d = c(1.23, 4.56, 7.89))
tbl <- tibble::tribble(
  ~ Feature,  ~ xtrm_max, ~ impute_max, ~ xtrm_min, ~ impute_min,
    "a",         NA,        NA,           NA,         NA,
    "b",         5,         5,            0,          1,
    "c",         9,         7,            7.1,        7.1
)
impute_predictors(x, tbl)
```

-----------

### Binding Data
* `bind_intersect()`
* `bind_union()`

```{r bind}
df1 <- data.frame(a = 1, b = 2, c = 3, row.names = "A")
df2 <- data.frame(a = 4, b = 5, d = 6, row.names = "B")
df3 <- data.frame(a = 7, b = 8, e = 9, row.names = "C")
list_df  <- list(a = df1, b = df2, c = df3)
list_df

bind_intersect(list_df)

bind_union(list_df)
```

-----------

### Stripping Data
* `refactor_data()`
* `strip_meta()`

```{r strip}
df <- data.frame(a = factor(c("a", "b")), b = 1:2)
foo <- df[df$a == "a", ]
foo

levels(foo$a)   # 2 levels! "b" is a ghost level

bar <- refactor_data(foo)
levels(bar$a)   # 1 level now
```

-----------

### `seq.xxxx.xx` formats
* `seq_lookup()`
* `seqify()`
* `lookup_anno()`

```{r seq-lookup}
seqs <- withr::with_seed(101, sample(names(s_data), 10))
seqs

# NAs for those analytes dropped from menu
seq_lookup(seqs)

seqify(seqs)

# Pass `apt.data` from appropriate ADAT
# to reconstitute those missing analytes
seq_lookup(seqs, splyr:::apt_data)

# OR: on the fly
seq_lookup(seqs, attr(s_data, "Col.Meta"))
```
